### ISSUE TITLE
[Feat] 지도 필터링, 검색 창 로직 구현 및 CSS 보완

### ISSUE THREAD

**Issue by eun6** [hanium-where2go/where2go-Frontend#10]
## 📌 Issue
지난 이슈에 끝내지 못한 필터링 항목들의 서버 통신 코드와 검색창 로직을 작성한다.

## 📝 To-do

- [ ] #17
- [ ] [필터] 주점 종류 서버 통신 코드 작성
- [ ] [필터] 주종 서버 통신 코드 작성
- [ ] [필터] 선호 지역 서버 통신 코드 작성
- [x] 검색창 로직 구현
- [x] [지도] 사용자 위치 기반 데이터 불러오는 코드 작성(상태 관리 포함)
- [x] [지도] 검색 데이터 받는 코드 작성
- [x] CSS 보완

## 📅 언제까지 할건가요?

- 2023.07.11. ~ 2023.07.15. (5일)

**Comment by eun6** [comment]
백엔드 api 문서 미완으로 서버 통신 로직은 추후 진행하기로 함.

[완료] 사용자 위치 기반 초기 주점 데이터 받는 로직, 검색 데이터 받는 로직, CSS 보완, 인원 수 등 필터링 slice로 상태관리
[진행 중] 필터(주점 종류, 주종, 선호지역) 서버 통신 코드
