### ISSUE TITLE
[FEAT]회원가입 약관 화면 구현, 기존화면 이미지 추가

### ISSUE THREAD

**Issue by nevertmr** [hanium-where2go/where2go-Frontend#13]
## 📌 Issue
회원가입 화면 구현
기존 첫 시작 화면 css 추가
필요 이미지 디자인에서 래스터화 하여 이미지 추가

## 📝 To-do

- [x] 첫 시작 화면 디자인
- [x] 첫 시작 화면 및 로그인 화면 이미지 첨부
- [x] 첫 시작 화면 및 로그인 화면 css 정리
- [x] 약관동의 화면 구현

## 📅 언제까지 할건가요?

- 2023.07.13. ~ 2023.07.17. (.5일 )
