### ISSUE TITLE
[FEAT] 마커 주점 표시, 주점 상세 페이지 화면 구현

### ISSUE THREAD

**Issue by eun6** [hanium-where2go/where2go-Frontend#18]
## 📌 Issue
주점 상세 페이지 화면 구현
1차 마커 눌렀을 때 모달 화면이 나와야 하고,
2차 모달을 화면 끝까지 당겼을 때 페이지 전환되며 상세 페이지가 나와야 함.

## 📝 To-do

- [x] 마커 눌렀을 때 모달 화면 표시
- [x] 주점 상세 화면 큰 틀 구현
- [ ] 시간이 되면 포스트맨 활용하여 필터링 부분 통신 로직 구현

## 📅 언제까지 할건가요?

- 2023.07.18. ~ 2023.07.23. (6일)
