### ISSUE TITLE
[DESIGN] 마이페이지 디자인

### ISSUE THREAD

**Issue by uiop5809** [hanium-where2go/where2go-Frontend#28]
## 📌 Issue
마이페이지 디자인

## 📝 To-do

- [ ] 마이페이지
- [ ] 포인트 사용 내역
- [ ] 예약 내역 + 리뷰 작성
- [ ] 리뷰내역
- [ ] 선호지역 업종 주종 설정, 선호 지역 관리
- [ ] 개인정보 수정, 회원탈퇴

## 📅 언제까지 할건가요?

- 2023.08.05~08.31
