### ISSUE TITLE
[DESIGN] 메인 페이지-주점상세 디자인

### ISSUE THREAD

**Issue by nevertmr** [hanium-where2go/where2go-Frontend#29]
## 📌 Issue
메인 페이지 디자인

## 📝 To-do
- [ ] 네이버 맵 npm 이해
- [ ] 기존 맵 페이지 ios에서 지도 안뜨는 오류 복구
- [ ] 주점 상세정보 디자인

## 📅 언제까지 할건가요?

- 2023.08.10. ~ 2023.08.12. (  3일  )
